# Generated by Django 5.0.2 on 2024-02-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_donationhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='current_amount',
            new_name='raised_sofar',
        ),
    ]
