# Generated by Django 5.0.2 on 2024-02-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_current_amount_project_raised_sofar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Images',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
