# Generated by Django 5.0.2 on 2024-02-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_alter_donation_user_alter_project_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='raised_sofar',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
