# Generated by Django 5.0.2 on 2024-02-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_project_raised_sofar_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical'), ('education', 'Education'), ('disaster', 'Disaster'), ('others', 'Others')], max_length=100),
        ),
    ]
