# Generated by Django 5.0.2 on 2024-02-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_project_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Images',
            new_name='images',
        ),
    ]
